### ISSUE TITLE
Deleted messages don't seem to get deleted properly

### ISSUE THREAD

**Issue by sussycatgirl** [revoltchat/.github#6]
### What happened?

When deleting a message, the delete event is emitted properly, but the message doesn't seem to be deleted from the database - After reloading the app, the message magically returns.

https://user-images.githubusercontent.com/26145882/168797020-d28037e6-b0bb-4c8e-8b29-92be79e65a23.MOV

**Comment by sussycatgirl** [comment]
HOW DID IT SEND ME TO THIS REPO WHAT THE FUCK GITHUB

**Comment by fatalerrorcoded** [comment]
i agree

**Comment by sussycatgirl** [comment]
wtf

https://user-images.githubusercontent.com/26145882/168798518-8a886d47-5d35-45a7-9e1e-c3476a34a38b.MOV

**Comment by Rexogamer** [comment]
Sounds like a GH Mobile bug
